
LF            equ  0x0A
CR            equ  0x0D
NULL          equ  0x00

TRUE          equ  1
FALSE         equ  0

EXIT_SUCCESS  equ  0
EXIT_FAILED   equ  1 

STDIN         equ  0
STDOUT        equ  1
STDERR        equ  2

SYS_read      equ  0
SYS_write     equ  1
SYS_open      equ  2
SYS_close     equ  3
SYS_fork      equ  57
SYS_exit      equ  60
SYS_creat     equ  85
SYS_time      equ  201


